name: flutter_playground
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.2.3
  draggable_scrollbar: ^0.1.0
  flutter_widget_from_html_core: ^0.8.4
  fwfh_selectable_text: ^0.8.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true